#!/usr/bin/env bash
set -eo pipefail

APP_DIR="${APP_DATA_DIR}"
mkdir -p "${APP_DIR}/postgres" "${APP_DIR}/wallet"

# ── Auto-detect Umbrel Monero node credentials ──────────────────────────────
UMBREL_MONERO_ENV="/home/umbrel/umbrel/app-data/monero/.env"
if [[ -f "$UMBREL_MONERO_ENV" ]]; then
  source "$UMBREL_MONERO_ENV"
  DAEMON_HOST="${APP_MONERO_NODE_IP:-10.21.21.179}"
  DAEMON_PORT="${APP_MONERO_RPC_PORT:-18081}"
  DAEMON_USER="${APP_MONERO_RPC_USER:-}"
  DAEMON_PASS="${APP_MONERO_RPC_PASS:-}"
  MONERO_NETWORK="${APP_MONERO_NETWORK:-mainnet}"
else
  DAEMON_HOST="${APP_MONERO_DAEMON_RPC_HOSTNAME:-host.docker.internal}"
  DAEMON_PORT="${APP_MONERO_DAEMON_RPC_PORT:-18089}"
  DAEMON_USER="${APP_MONERO_DAEMON_RPC_USERNAME:-}"
  DAEMON_PASS="${APP_MONERO_DAEMON_RPC_PASSWORD:-}"
  MONERO_NETWORK="mainnet"
fi

# User overrides (takes precedence over auto-detect)
DAEMON_HOST="${APP_MONERO_DAEMON_RPC_HOSTNAME:-$DAEMON_HOST}"
DAEMON_PORT="${APP_MONERO_DAEMON_RPC_PORT:-$DAEMON_PORT}"
DAEMON_USER="${APP_MONERO_DAEMON_RPC_USERNAME:-$DAEMON_USER}"
DAEMON_PASS="${APP_MONERO_DAEMON_RPC_PASSWORD:-$DAEMON_PASS}"

# Wallet RPC runs inside our compose network
WALLET_RPC="${APP_MONERO_WALLET_RPC_ENDPOINT:-http://wallet-rpc:18082/json_rpc}"
WALLET_USER="${APP_MONERO_WALLET_RPC_USERNAME:-}"
WALLET_PASS="${APP_MONERO_WALLET_RPC_PASSWORD:-}"

# MoneroPay
MP_URL="${APP_MONEROPAY_BASE_URL:-http://host.docker.internal:5000}"
MP_CALLBACK="${APP_MONEROPAY_CALLBACK_URL:-http://monero-merchant_backend_1:8080/callback/}"

# Admin password
ADMIN_PASSWORD="${APP_ADMIN_PASSWORD:-changeme}"

# ── Generate secrets file if it doesn't exist ────────────────────────────────
SECRETS_FILE="${APP_DIR}/.secrets"
if [ ! -f "${SECRETS_FILE}" ]; then
  cat > "${SECRETS_FILE}" <<EOF
# Auto-generated secrets for Monero Merchant
DB_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)
JWT_REFRESH_SECRET=$(openssl rand -hex 32)
JWT_MONEROPAY_SECRET=$(openssl rand -hex 32)
JWT_LWS_TOKEN=$(openssl rand -hex 32)
WALLET_PASSWORD=$(openssl rand -hex 16)
EOF
  chmod 600 "${SECRETS_FILE}"
fi

# Source secrets for use in .env generation
while IFS='=' read -r key value; do
  [[ "$key" =~ ^[[:space:]]*# ]] && continue
  [[ -z "$key" ]] && continue
  eval "export ${key}=\"${value}\""
done < "${SECRETS_FILE}"

# Build daemon RPC endpoint
DAEMON_ENDPOINT="http://${DAEMON_HOST}:${DAEMON_PORT}/json_rpc"

# Build wallet-rpc daemon-login flag (omit if empty)
if [[ -n "$DAEMON_USER" ]]; then
  DAEMON_LOGIN_OPT="--daemon-login=${DAEMON_USER}:${DAEMON_PASS}"
else
  DAEMON_LOGIN_OPT=""
fi

# ── Write .env for the backend and postgres ────────────────────────────────
ENV_FILE="${APP_DIR}/.env"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by exports.sh — do not edit manually
ADMIN_NAME=admin
ADMIN_PASSWORD=${ADMIN_PASSWORD}
PORT=8080

DB_HOST=db
DB_USER=moneromerchant
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=moneromerchant
DB_PORT=5432

JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_MONEROPAY_SECRET=${JWT_MONEROPAY_SECRET}
JWT_LWS_TOKEN=${JWT_LWS_TOKEN}

MONEROPAY_BASE_URL=${MP_URL}
MONEROPAY_CALLBACK_URL=${MP_CALLBACK}

MONERO_DAEMON_RPC_ENDPOINT=${DAEMON_ENDPOINT}
MONERO_DAEMON_RPC_HOSTNAME=${DAEMON_HOST}
MONERO_DAEMON_RPC_PORT=${DAEMON_PORT}
MONERO_DAEMON_RPC_USERNAME=${DAEMON_USER}
MONERO_DAEMON_RPC_PASSWORD=${DAEMON_PASS}

MONERO_WALLET_RPC_ENDPOINT=${WALLET_RPC}
MONERO_WALLET_RPC_USERNAME=${WALLET_USER}
MONERO_WALLET_RPC_PASSWORD=${WALLET_PASS}

POSTGRES_DB=moneromerchant
POSTGRES_USER=moneromerchant
POSTGRES_PASSWORD=${DB_PASSWORD}

WALLET_NAME=merchant_wallet
WALLET_PASSWORD=${WALLET_PASSWORD}
WALLET_AUTO_REFRESH_PERIOD=2

# Wallet-RPC service config
MONERO_NETWORK=${MONERO_NETWORK}
MONERO_DAEMON_HOST=${DAEMON_HOST}
MONERO_DAEMON_PORT=${DAEMON_PORT}
MONERO_WALLET_RPC_PORT=18082
MONERO_WALLET_RPC_DAEMON_LOGIN=${DAEMON_LOGIN_OPT}
EOF

chmod 600 "${ENV_FILE}"
